blank_issues_enabled: false
default_label: ''
contact_links:
  - name: 💬 Questions & Support
    url: https://github.com/standard-group/mesa-client/discussions
    about: Please ask and answer questions here.
