name: Android Build - Ubuntu

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    name: Build Mesa Android on Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17 (required by Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install pnpm
        run: npm install -g pnpm@10

      - name: Install Rust with Android target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Install project dependencies
        run: pnpm install --no-frozen-lockfile

      - name: Install Android SDK and NDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true

      - name: Set Android build env
        run: |
          echo "MESA_BUILD_TYPE=nightly" >> $GITHUB_ENV
          echo "TAURI_ANDROID_TARGET=aarch64-linux-android" >> $GITHUB_ENV
          echo "JAVA_HOME=$JAVA_HOME" >> $GITHUB_ENV
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_NDK_HOME" >> $GITHUB_ENV

      - name: Initialize Tauri Android project
        run: pnpm tauri android init

      - name: Build Android APK
        run: pnpm tauri android build --apk

      - name: Get build date (UTC)
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Upload Android APK
        uses: actions/upload-artifact@v4
        with:
          name: mesa-android-nightly-${{ steps.date.outputs.date }}
          path: src-tauri/gen/android/app/build/outputs/apk/release/*.apk
