name: Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-android:
    name: Build Tauri Android APK
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 12266719
          accept-android-sdk-licenses: true

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android

      - name: Set environment variables for Android
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "JAVA_HOME=${JAVA_HOME_17}" >> $GITHUB_ENV
          echo "NDK_HOME=$ANDROID_SDK_ROOT/ndk-bundle" >> $GITHUB_ENV
        shell: pwsh

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install dependencies
        run: pnpm install

      - name: Initialize Android project
        run: pnpm tauri android init || echo "Already initialized"

      - name: Build APK
        run: pnpm tauri android build --apk
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
          NDK_HOME: ${{ env.NDK_HOME }}
          OPENSSL_STATIC: 1
          OPENSSL_NO_VENDOR: 0

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mesa-client-android-apk
          path: src-tauri/gen/android/app/build/outputs/apk/**/*.apk