name: Mobile Build Mesa – Android (nightly)

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build for Android (armv7 + aarch64 + x86 + x86_64)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install Rust + Android targets
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android,armv7-linux-androideabi,i686-linux-android,x86_64-linux-android

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Set up Android SDK & NDK
        uses: android-actions/setup-android@v3
        with:
          extra-packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;25.2.9519653

      - name: Locate installed NDK 25.2.9519653
        id: ndk-path
        run: |
          ndk_path=$(dirname "$(find "$ANDROID_SDK_ROOT" -type f -name ndk-build | grep -E '25\.2\.9519653' | head -n1)")
          echo "NDK_ROOT=$ndk_path" >> $GITHUB_ENV
          echo "NDK_HOME=$ndk_path" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ndk_path" >> $GITHUB_ENV
          echo "Found NDK at $ndk_path"

      - name: Verify NDK path exists
        run: ls -la "$ANDROID_NDK_ROOT"

      - name: Install frontend deps
        run: pnpm install

      - name: Tauri Android init (CI mode)
        run: pnpm tauri android init --ci
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.NDK_HOME }}

      - name: Build APK for all targets
        run: pnpm tauri android build --apk
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
          NDK_HOME: ${{ env.NDK_HOME }}

      - name: Get build date (UTC)
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mesa-android-nightly-${{ steps.date.outputs.date }}
          path: |
            src-tauri/gen/android/app/build/outputs/apk/**/*.apk
